[env:hub]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<*.cpp> -<main_minimal.cpp> -<controller.cpp> -<controller_new.cpp> -<hub.cpp>
lib_deps = 
    bblanchon/ArduinoJson@^6.21.4
    lovyan03/LovyanGFX@^1.1.12
    WebServer@^2.0.0
    https://github.com/HamzaYslmn/esp32-tunnel.git
build_flags = 
    -D MODE_HUB
    -D CORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -D NDEBUG
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LGFX_NO_FONT_IPA
    -D LGFX_NO_FONT_JPN
    -D LGFX_NO_FONT_KOR
    -D LGFX_NO_FONT_CN
    -D LGFX_NO_FONT_TW

[env:controller]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port = COM4
build_src_filter = +<*.cpp> -<main_minimal.cpp> -<controller.cpp> -<controller_new.cpp> -<hub.cpp>
lib_deps = 
    bblanchon/ArduinoJson@^6.21.4
    lovyan03/LovyanGFX@^1.1.12
    h2zero/NimBLE-Arduino@^1.4.0
    WebServer@^2.0.0
build_flags = 
    -D MODE_CONTROLLER
    -D CORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -D NDEBUG
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LGFX_NO_FONT_IPA
    -D LGFX_NO_FONT_JPN
    -D LGFX_NO_FONT_KOR
    -D LGFX_NO_FONT_CN
    -D LGFX_NO_FONT_TW
